language: rust
before_install :
     - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libgtk3.0-dev ; fi
script:
     - cargo install cargo-vcpkg
     - cargo vcpkg build
     - cargo test --release      
jobs:
    include:        
        - dist : bionic
        - os : windows 