language: rust

script:
     - cargo install cargo-vcpkg
     - cargo vcpkg build
     - cargo test --release 
     
jobs:
    include:        
        - dist : bionic
          before_install :
          	- sudo apt-get install libgtk2.0-dev
        - os : windows 