os: windows

matrix:
    include:        
        - language: rust
          script:
            - cargo install cargo-vcpkg
            - cargo vcpkg build
            - cargo test --release 
          